travis:
  secure:
    BINSTAR_TOKEN: G0KeiWvzSWMGTuVyLF1nxML+esraHfecxOQCTAMIWesdDsvE6zjqzJTO5Tpd7aZRNx09vyVYdZX3/3PJ16baithaxwLfaGyFubKQfUF8mYoEyIW3ib8nOwwLDJvmYN06250jnuadKNN3bi6Ikt0jYptfmpiqM8fTERgsO/htGMJneMNGucr17sxF3E1lwx6wCvtSwBqeR+a9wZLBBvEN498aCusI4ooGkEBMBhijL5o5Xlhj2znb/ay7c9GA2DeAjbFWv722DXWEa2dTd1v6g//7H8KOUdAWOctn4YwQR4P8IJ+XzKkERZnWUj0iKWEvL/6EE6EMCKuMPqslZ9poEzgFLGzmCtCXlrXMj7ZRJdTqdRDUL9AVmt1z5yU3GegDGyc0ZFiVQPi5xScpSAOLUaJlAn+R0uV73Nyzc4PDVIB2qoVaR8hdsYub7giqwJI/zXy4SLddOzLV2c3R+kBZEurTWr1c5o1X3AhZgTkdCXCGxaM9x79akBpbji3mh3NZwhDhTTmOP4f4Mit2bTvAMkrTcGtY4kq2u2Jl+cthGrvGxQPUl7KugezAeMEt7iYhu7kyPA8ha/9pR6qc91FnG9yfDZgx/2YvJ5xqbp2gne2Foc8n4NVf/W1kEaQ17IN1Iyr7m+DF4xqWkHO6oNNdIYA2GwVqgGXAp9RLs5fWP04=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
